// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA37K-n41Evahm1tOy28q5ISyzUTR5FHJ0',
    appId: '1:930619561034:web:3c6156b5a66c66b3ac42b3',
    messagingSenderId: '930619561034',
    projectId: 'case-study-hero-games',
    authDomain: 'case-study-hero-games.firebaseapp.com',
    storageBucket: 'case-study-hero-games.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOixIgw1rPkWF7aDm6HTpbUScnejMxmE',
    appId: '1:930619561034:android:a8f15c53d406b0beac42b3',
    messagingSenderId: '930619561034',
    projectId: 'case-study-hero-games',
    storageBucket: 'case-study-hero-games.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTmAaXjX4WYQatPPe3trowwDHKOXpkXQg',
    appId: '1:930619561034:ios:9adccba651fc3f2dac42b3',
    messagingSenderId: '930619561034',
    projectId: 'case-study-hero-games',
    storageBucket: 'case-study-hero-games.appspot.com',
    iosBundleId: 'com.example.heroGamesCaseStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTmAaXjX4WYQatPPe3trowwDHKOXpkXQg',
    appId: '1:930619561034:ios:55f8cdb3e9102e02ac42b3',
    messagingSenderId: '930619561034',
    projectId: 'case-study-hero-games',
    storageBucket: 'case-study-hero-games.appspot.com',
    iosBundleId: 'com.example.heroGamesCaseStudy.RunnerTests',
  );
}
